apiVersion: apps/v1
kind: Deployment
metadata:
  name: seyoawe-engine
spec:
  replicas: 2 # This creates 2 copies (pods) of your Flask server for load balancing
  selector:
    matchLabels:
      app: seyoawe-engine
  template:
    metadata:
      labels:
        app: seyoawe-engine
    spec:
      containers:
      - name: seyoawe-engine-container
        cpu: "250m" # Limit CPU usage to 500 millicores (0.25 CPU)
        image: Denis1988/your-flask-image:latest # Your Docker Hub image
        ports:
        - containerPort: 5000 # The port your Flask app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: seyoawe-engine-svc # This becomes the DNS name for the CLI app to use
spec:
  selector:
    app: seyoawe-engine
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000