---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seyoawe-engine
  labels:
    app: seyoawe-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seyoawe-engine
  template:
    metadata:
      labels:
        app: seyoawe-engine
    spec:
      containers:
      - name: seyoawe-engine-container
        image: denis20/seyoawe-engine:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "250m"
        command: ["/bin/sh", "-c"]
        args: ["./run.sh linux"]
        
        ports:
        - containerPort: 8080   # Changed from 5000 to 8080 to match what your run.sh outputs
---
apiVersion: v1
kind: Service
metadata:
  name: seyoawe-engine-svc
spec:
  selector:
    app: seyoawe-engine
  ports:
    - protocol: TCP
      port: 8080           
      targetPort: 8080     # Changed to 8080 so traffic reaches Flask correctly