FROM python:3.13.12-slim

# Set the working directory first
WORKDIR /opt/seyoawe-engine

# Copy everything into the working directory
COPY . .

# Inform Docker that the container listens on port 5000
EXPOSE 5000

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

RUN sed -i 's/\r$//' run.sh
RUN chmod +x run.sh
# Also make the actual binary executable!
RUN chmod +x seyoawe.linux
CMD ["./run.sh", "linux"]